### ISSUE TITLE
Typing "\u" to project search causes Mayday

### ISSUE THREAD

**Issue by gagarski** [vorpal-research/kotoed#76]
Probably we need a fix to `String.toQuery()`:

https://github.com/vorpal-research/kotoed/blob/c49c7215c173c9b4cd308a7ab31264c80874353f/kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/db/condition/lang/Util.kt#L7

**Comment by belyaev-mikhail** [comment]
um? Seems to work for me

**Comment by belyaev-mikhail** [comment]
![image](https://user-images.githubusercontent.com/2496075/64864151-22677500-d63f-11e9-9b0d-a658cad9a40d.png)

**Comment by gagarski** [comment]
My fault, `\` works but `\u` does not.

**Comment by belyaev-mikhail** [comment]
Okay. It not only breaks project search, but any search we have)

**Comment by belyaev-mikhail** [comment]
Also, seems like \u is the only combination that triggers this. Kinda facsinating, really.

**Comment by belyaev-mikhail** [comment]
Okay, it's a double decoding problem. '\t' actually translates into a tab, too.

**Comment by belyaev-mikhail** [comment]
Fixed 001954e8
